// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyDiagnostics() {
  return window['go']['main']['App']['CopyDiagnostics']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallAndStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallAndStart'](arg1, arg2, arg3);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
