// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyDiagnostics():Promise<string>;

export function GetStatus():Promise<main.GUIStatus>;

export function InstallAndStart(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Restart():Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
